name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Mint
        uses: fabasoad/setup-mint-action@main
        with:
          version: 0.12.0

      - name: Install Dependencies
        run: mint install
        
      - name: Build
        run: mint build
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0.12
        with:
          publish-dir: dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
